global using Ink_Canvas.Controllers.Automation;
global using Ink_Canvas.Controllers.Input;
global using Ink_Canvas.Controllers.Presentation;
global using Ink_Canvas.Controllers.Workspace;
global using Ink_Canvas.Helpers;
global using Ink_Canvas.Features.Automation.Coordinators;
global using Ink_Canvas.Features.Automation.Hosts;
global using Ink_Canvas.Features.Automation.Services;
global using Ink_Canvas.Features.Ink.Coordinators;
global using Ink_Canvas.Features.Ink.Hosts;
global using Ink_Canvas.Features.Ink.Models;
global using Ink_Canvas.Features.Ink.Services;
global using Ink_Canvas.Features.Ink.State;
global using Ink_Canvas.Features.Presentation.Coordinators;
global using Ink_Canvas.Features.Presentation.Hosts;
global using Ink_Canvas.Features.Presentation.Services;
global using Ink_Canvas.Features.Presentation.State;
global using Ink_Canvas.Features.Settings.Coordinators;
global using Ink_Canvas.Features.Settings.Hosts;
global using Ink_Canvas.Features.Shell.Coordinators;
global using Ink_Canvas.Features.Shell.Hosts;
global using Ink_Canvas.Features.Shell.State;
global using Ink_Canvas.Services.Settings;
global using Ink_Canvas.Services.System;
global using Ink_Canvas.Services.System.Integration;
global using Ink_Canvas.ViewModels.Automation;
global using Ink_Canvas.ViewModels.Ink;
global using Ink_Canvas.ViewModels.Main;
global using Ink_Canvas.ViewModels.Presentation;
global using Ink_Canvas.ViewModels.Settings;
global using Ink_Canvas.ViewModels.Shell;
global using Ink_Canvas.ViewModels.Workspace;
global using CommitReason = Ink_Canvas.Features.Ink.Models.CommitReason;
global using InkCanvasEditingMode = System.Windows.Controls.InkCanvasEditingMode;
global using StylusPointCollection = System.Windows.Input.StylusPointCollection;
