name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0

    # 安装 .NET SDK
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore "Ink Canvas Modern.sln"

    # 编译整个项目
    - name: Build the solution
      run: |
        dotnet build "Ink Canvas Modern.sln" -c Release -p:Platform="Any CPU" --no-restore /p:GitFlow="Github Action"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the solution (x64)
      run: |
        dotnet build "Ink Canvas Modern.sln" -c Release -p:Platform="x64" --no-restore /p:GitFlow="Github Action"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the solution (ARM64)
      run: |
        dotnet build "Ink Canvas Modern.sln" -c Release -p:Platform="ARM64" --no-restore /p:GitFlow="Github Action"
      env:
        Configuration: ${{ matrix.configuration }}
        
    # 上传编译成品
    - name: Upload to artifact
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Modern
        path: Ink Canvas/bin/Release
        
    - name: Upload to artifact (x64)
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Modern (x64)
        path: Ink Canvas/bin/x64/Release
        
    - name: Upload to artifact (ARM64)
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Modern (ARM64)
        path: Ink Canvas/bin/ARM64/Release

